source :rubygems

gem 'adsf'
gem 'builder'
gem 'haml'
gem 'kramdown'
gem 'less'
gem 'mime-types'
gem 'nanoc', ">= 3.4.2"
gem 'nokogiri'
gem 'pygmentize'
gem 'systemu'
gem 'therubyracer'
gem 'w3c_validators'
gem 'yui-compressor'
