source "https://rubygems.org"

gem 'adsf'
gem 'builder'
gem 'haml'
gem 'kramdown', "= 0.13.4"
gem 'less'
gem 'mime-types'
gem 'nanoc', ">= 3.4.2"
gem 'nokogiri'
gem 'pygmentize'
gem 'systemu'
gem 'therubyracer'
gem 'w3c_validators'
gem 'yui-compressor'
